Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TrainingWebsite.Controllers
{
    public class ContactController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrainingWebsite.Models;
using TrainingWebsite.Models.ViewModels;

namespace TrainingWebsite.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IProductRepository productRepository, ShoppingCart shoppingCart)
        {
            _productRepository = productRepository;
            _shoppingCart = shoppingCart;
        }
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int productId)
        {
            var selectedProducts = _productRepository.AllProducts.FirstOrDefault(p => p.ProductId == productId);

            if (selectedProducts != null)
            {
                _shoppingCart.AddToCart(selectedProducts, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int productId)
        {
            var selectedProducts = _productRepository.AllProducts.FirstOrDefault(p => p.ProductId == productId);

            if (selectedProducts != null)
            {
                _shoppingCart.RemoveFromCart(selectedProducts);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Carousel.cshtml
<div class="cols-md-6">

    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/Images/hello_world_1024x1024.jpg" alt="First slide" style="height:400px">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/Images/pic-3.jpg" alt="Second slide" style="height:400px">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/Images/blanket.jpg" alt="Third slide" style="height:400px">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/Images/pic-1.jpg" alt="Fourth slide" style="height:400px">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]TrainingWebsite</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/lib/jquery/jquery.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
   
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">
                    MH Embroidery
                    <div class="row-cols-md-3">
                        <img class="img-responsive" alt="Training Website" src="~/Images/daffodil.jpg" style="height:70px; width:70px; border-radius: 20px" />
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Home" asp-action="List">Home<span class="sr-only">(current)</span></a>
                        </li>
                        @await Component.InvokeAsync("CategoryMenu")
                        <li class="nav-item">
                            <a asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        @await Component.InvokeAsync("ShoppingCartSummary")
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container" id="body">
            <div class="row">
                <div class="col-md-12">
                    @RenderBody()
                </div>
            </div>
        </div>
    
    <div class="card-footer text-muted">
    <div class="container">
        &copy; 2020 - TrainingWebsite
    </div>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_ProductCard.cshtml
@model Products


    <div class="col-sm-4 col-lg-6 col-md-3">
        <div class="thumbnail">
            @*<img src="@Model.ImageThumbnailUrl" alt="" />*@
            <img src="~/Images/blanket.jpg" alt="" style="height:100px; width:100px;"/>
            <div class="caption">
                <h3 class="pull-right">@Model.Price.ToString("c")</h3>
                <h3>
                    <a asp-controller="Products" asp-action="Details" asp-route-id="@Model.ProductId">@Model.ProductName</a>
                </h3>
                <p>@Model.ShortDescription</p>
            </div>
            <div class="addToCart">
                <p class="button">
                    <a class="btn btn-primary"
                       asp-controller="ShoppingCart"
                       asp-action="AddToShoppingCart"
                       asp-route-productId="@Model.ProductId">
                        Add To Basket
                    </a>
                </p>
            </div>
        </div>
    </div>